### ISSUE TITLE
App icons are too big

### ISSUE THREAD

**Issue by nsourov** [elementary/wingpanel#404]
The app icon sizes are too big. It looks very bad on my big screen.

![image](https://user-images.githubusercontent.com/29119872/128588778-c6dfb0ac-6bc1-4e56-92fb-26c6471d5fa6.png)

Is there any way to reduce the icon size?
I tried updating this code in `~/.config/gtk-3.0/gtk.css` this file
```css
/* source: https://github.com/mdh34/elementary-indicators/issues/1 */
.composited-indicator {
    padding: 0 2px;
    font-size: 10px;
}
```
